### ISSUE TITLE
How to use the "Pester Task" in my YAML file for Azure Pipelines?

### ISSUE THREAD

**Issue by PatrickGrub** [rfennell/vNextBuild#390]
#### Where are you running it?

- Azure DevOps Service (VSTS), acutally I use Azure Pipelines

#### Expected behaviour and actual behaviour

**I want to use this Task in my YAML file**, but unfortunately I cannot find the documentation how I can insert it.
For example like the default [Copy Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/copy-files?view=vsts). Therefore I would require the "Taskname" `Task` and all the possible options via YAML.
Because in Azure Pipelines I can not find the GUI like in the documentation for adding a new Build Step, it looks like you are using another Version of the Cloud Service:

![pipeline](https://user-images.githubusercontent.com/36075173/47415572-054e5d00-d774-11e8-8cd1-adabb45bf03a.png)

**Comment by ChrisLGardner** [comment]
Our docs are currently out of date for this as it's not a feature I've made much use of yet. I'll aim to get these updated in the next few weeks, I'm on holiday for now so I'll sort it when I'm back with a real pc.

In the meantime if you create a build in the UI, add the pester step and then click the export to yaml button it should show you exactly what you want.
________________________________

**Comment by PatrickGrub** [comment]
Thanks for the very quick answer @ChrisLGardner !

Then, I will wait for your update, because in my Azure Pipelines it is **not possible** to add the Task via GUI, only in "Releases" and that's not the location where I want to use it.

Have a great holiday my friend ;)

**Comment by rfennell** [comment]
I needs to get the documentation for yaml usage for all the tasks in the wiki. Should have done it a while ago

**Comment by PatrickGrub** [comment]
@rfennell Can I find out all the information inside the file [task.json](https://github.com/rfennell/vNextBuild/blob/master/Extensions/Pester/task/task.json)?

So I am right if
+ Taskname is `31EF0033-64E3-4C55-B888-F446541474A6` ?
+ Possible options found under the json attribute `input`?

**Comment by rfennell** [comment]
Yes the task.Json file has all the details, that is what I need to transpose to the wiki. I wonder if there is a tool to do it, or will I have to write one?

**Comment by ChrisLGardner** [comment]
I'd just add each task to a build, set values for all the properties and then use the export to yaml functionality to get the majority of that data out of it. I'm pretty sure the name of the task is a little weird for yaml but I can't remember why.
________________________________

**Comment by rfennell** [comment]
I am working on documentation for all the task in YAML, writing a tools to export the task.json as markdown documentation

**Comment by rfennell** [comment]
@PatrickGrub  Will this do you [YAML documentation](https://github.com/rfennell/vNextBuild/wiki/Pester-Task-YAML)?

**Comment by PatrickGrub** [comment]
I just tested following YAML

```YAML
- task: Pester@1
  inputs:
    scriptFolder: '$(Build.SourcesDirectory)' 
    resultsFile: '$(Build.SourcesDirectory)\Test-Pester.XML'
```

Because I have compared it with the [task.json from the Copy task](https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesV2/task.json) and it looks like we should use the `Name` from the task.json as `Task` in the YAML.

The \"@1" means which version, but when building it shows me following error:
`Job Job1: Step references task 'Pester' at version '1' which does not exist.`

![error_pester](https://user-images.githubusercontent.com/36075173/47496294-ab729380-d856-11e8-88df-55f014323b30.png)

I got sure it is installed because in `Releases` I can Add Task "Pester Test Runner from Black Marble".

**Comment by rfennell** [comment]
I have just update the auto documentation generated tool, see if looks better to you

It generated, as the required variables

```
# Pester Test Runner from Black Marble
# Description - Run Pester tests by either installing the latest version of Pester at run time (if possible) or using the version shipped with the task (4.3.1)
- task: Pester
  inputs: 
     # Required arguments
     scriptFolder: $(System.DefaultWorkingDirectory)\*
     resultsFile: $(System.DefaultWorkingDirectory)\Test-Pester.XML
     run32Bit: False
```

As to your @1, the shipping version is @8, we don't ship old versions in the extension
